version: "3"

services: 
  # Information it's add when the container it's generated
  db:
    image: mariadb:10.6.2-focal
    container_name: db_test
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"       
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: market_app
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    restart: unless-stopped
    # volumes: 
    #   - ./sql:/docker-entrypoint-initdb.d/:rw 
    ports:
      - "3306:3306"
    networks:
      - db_spring_boot

# volumes:
#   db.sql:

networks: 
  db_spring_boot:
