server:
    port: 8080 
spring:
    mvc:
      pathmatch:
        matching-strategy: ANT_PATH_MATCHER
    security:
      user:
        name: test
        password: test
        roles:
        - SUPERUSER   
    datasource:
      url: jdbc:mariadb://172.23.0.2:3306/market_app
      username: root
      password: root
    # sql:
    #   init:
    #     mode: embedded     
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
      open-in-view: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MariaDB102Dialect

management:
  server:
    base-path: /manage
    port: 9000
  endpoints:
    web:
      exposure:
        include:
          - "*"
